#pragma once

// Helper macro
#define FX_ANSI_STRINGIFY(v) #v
#define FX_ANSI_STRINGIFY_LAYERED(v) 	FX_ANSI_STRINGIFY(v)

// Default macros
#define FX_ANSI_ESCAPE					"\x1b"
#define FX_ANSI_STYLE(c)				FX_ANSI_ESCAPE "[" FX_ANSI_STRINGIFY(c) "m"
#define FX_ANSI_FG_STYLE_256(c)			FX_ANSI_ESCAPE "[38;5;" FX_ANSI_STRINGIFY(c) "m"
#define FX_ANSI_BG_STYLE_256(c)			FX_ANSI_ESCAPE "[48;5;" FX_ANSI_STRINGIFY(c) "m"
#define FX_ANSI_RESET					FX_ANSI_STYLE(0)

// Colors (FG)
#define FX_ANSI_FG_BLACK				FX_ANSI_STYLE(30)
#define FX_ANSI_FG_RED					FX_ANSI_STYLE(31)
#define FX_ANSI_FG_GREEN				FX_ANSI_STYLE(32)
#define FX_ANSI_FG_YELLOW				FX_ANSI_STYLE(33)
#define FX_ANSI_FG_BLUE					FX_ANSI_STYLE(34)
#define FX_ANSI_FG_MAGENTA				FX_ANSI_STYLE(35)
#define FX_ANSI_FG_CYAN					FX_ANSI_STYLE(36)
#define FX_ANSI_FG_WHITE				FX_ANSI_STYLE(37)
#define FX_ANSI_FG_RGB(r, g, b)			FX_ANSI_ESCAPE "[38;2;" FX_ANSI_STRINGIFY(r) ";" FX_ANSI_STRINGIFY(g) ";" FX_ANSI_STRINGIFY(b) "m"
#define FX_ANSI_FG_DEFAULT				FX_ANSI_STYLE(39)

// Colors (BG)
#define FX_ANSI_BG_BLACK				FX_ANSI_STYLE(40)
#define FX_ANSI_BG_RED					FX_ANSI_STYLE(41)
#define FX_ANSI_BG_GREEN				FX_ANSI_STYLE(42)
#define FX_ANSI_BG_YELLOW				FX_ANSI_STYLE(43)
#define FX_ANSI_BG_BLUE					FX_ANSI_STYLE(44)
#define FX_ANSI_BG_MAGENTA				FX_ANSI_STYLE(45)
#define FX_ANSI_BG_CYAN					FX_ANSI_STYLE(46)
#define FX_ANSI_BG_WHITE				FX_ANSI_STYLE(47)
#define FX_ANSI_BG_RGB(r, g, b)			FX_ANSI_ESCAPE "[48;2;" FX_ANSI_STRINGIFY(r) ";" FX_ANSI_STRINGIFY(g) ";" FX_ANSI_STRINGIFY(b) "m"
#define FX_ANSI_BG_DEFAULT				FX_ANSI_STYLE(49)

// Styles
#define FX_ANSI_BEGIN_BOLD				FX_ANSI_STYLE(1)
#define FX_ANSI_END_BOLD				FX_ANSI_STYLE(22)
#define FX_ANSI_BEGIN_FAINT				FX_ANSI_STYLE(2)
#define FX_ANSI_END_FAINT				FX_ANSI_STYLE(22)
#define FX_ANSI_BEGIN_ITALIC			FX_ANSI_STYLE(3)
#define FX_ANSI_END_ITALIC				FX_ANSI_STYLE(23)
#define FX_ANSI_BEGIN_UNDERLINE			FX_ANSI_STYLE(4)
#define FX_ANSI_END_UNDERLINE			FX_ANSI_STYLE(24)
#define FX_ANSI_BEGIN_BLINKING			FX_ANSI_STYLE(5)
#define FX_ANSI_END_BLINKING			FX_ANSI_STYLE(25)
#define FX_ANSI_BEGIN_INVERT			FX_ANSI_STYLE(7)
#define FX_ANSI_END_INVERT				FX_ANSI_STYLE(27)
#define FX_ANSI_BEGIN_HIDDEN			FX_ANSI_STYLE(8)
#define FX_ANSI_END_HIDDEN				FX_ANSI_STYLE(28)
#define FX_ANSI_BEGIN_STRIKETHROUGH		FX_ANSI_STYLE(9)
#define FX_ANSI_END_STRIKETHROUGH		FX_ANSI_STYLE(29)

// Style wrappers
#define FX_ANSI_BOLD(str)				FX_ANSI_BEGIN_BOLD			str	FX_ANSI_END_BOLD
#define FX_ANSI_FAINT(str)				FX_ANSI_BEGIN_FAINT			str	FX_ANSI_END_FAINT
#define FX_ANSI_ITALIC(str)				FX_ANSI_BEGIN_ITALIC		str	FX_ANSI_END_ITALIC
#define FX_ANSI_UNDERLINE(str)			FX_ANSI_BEGIN_UNDERLINE		str	FX_ANSI_END_UNDERLINE
#define FX_ANSI_BLINKING(str)			FX_ANSI_BEGIN_BLINKING		str	FX_ANSI_END_BLINKING
#define FX_ANSI_INVERT(str)				FX_ANSI_BEGIN_INVERT		str	FX_ANSI_END_INVERT
#define FX_ANSI_HIDDEN(str)				FX_ANSI_BEGIN_HIDDEN		str	FX_ANSI_END_HIDDEN
#define FX_ANSI_STRIKETHROUGH(str)		FX_ANSI_BEGIN_STRIKETHROUGH	str	FX_ANSI_END_STRIKETHROUGH