#!/usr/bin/env python3
import subprocess
import hashlib
import datetime
import os
import getpass
import socket

enable_fingerprint = os.getenv("DO_FINGERPRINT", "false").lower() == "true"
output_file = "generated/version.hpp"

def run_cmd(command: str, default: str = "unknown") -> str:
    try:
        return subprocess.check_output(command, shell=True, text=True).strip()
    except subprocess.CalledProcessError:
        return default

commit_hash = run_cmd("git rev-parse --short HEAD", "unknown")
branch_name = run_cmd("git rev-parse --abbrev-ref HEAD", "unknown-branch")

# Detect if working directory has uncommitted changes
is_dirty = run_cmd("git diff --quiet || echo dirty", "").strip() == "dirty"
if is_dirty:
    commit_hash += "-dirty"

host_name = socket.gethostname()
user_name = getpass.getuser()
timestamp = datetime.datetime.now().strftime("%y%m%d-%H%M")

version_major = "0"
version_minor = "0"
version_patch = "0"

tag = run_cmd("git describe --tags --abbrev=0", "")
tag_commit = run_cmd(f"git rev-list -n 1 {tag}", "unknown")
is_tag_commit = tag_commit == run_cmd("git rev-parse HEAD", "unknown")

if not is_tag_commit:
	tag = f"vNext ({commit_hash})"

fingerprint = "0"
fingerprint_src = (
    f"{version_major}-{version_minor}-{version_patch}-{commit_hash}-"
    f"{branch_name}-{host_name}-{user_name}-{timestamp}"
)
fingerprint = hashlib.sha1(fingerprint_src.encode()).hexdigest()[:16]

os.makedirs(os.path.dirname(output_file), exist_ok=True)

with open(output_file, "w") as f:
    f.write("// Auto-generated version header. Do not edit manually.\n")
    f.write("// Generated by tools/update_git.py\n\n")
    f.write("#pragma once\n\n")
    f.write(f'#define BUILD_VERSION_STRING "{tag}"\n')
    f.write(f'#define BUILD_COMMIT_HASH "{commit_hash}"\n')
    f.write(f'#define BUILD_BRANCH_NAME "{branch_name}"\n')
    f.write(f'#define BUILD_HOST_NAME "{host_name}"\n')
    f.write(f'#define BUILD_USER_NAME "{user_name}"\n')
    f.write(f'#define BUILD_TIMESTAMP "{timestamp}"\n')
    f.write(f'#define BUILD_FINGERPRINT "{fingerprint}"\n')

print(f"Version header generated at: {output_file}")
print(f"Version: {commit_hash}")
